### ISSUE TITLE
Strange behavior of msgJson.Code :=

### ISSUE THREAD

**Issue by levran197** [badunius/myJSON#1]
Hi,

A sample:
   msgJson := myJSONItem.Create;
   msgJson.Code := '{"type":"auth","login":"guy","pass":"guy"}';
   memo2.lines.add(msgJson.Code);
    // shows **_{"type":"auth","login":"guy","pass":"guy"}_**

   msgJson.Code := '{"type":"auth","action":"end","auth":true}';
   memo2.lines.add(msgJson.Code);
  // shows **_{"type":"auth","login":"guy","pass":"guy","action":"end","auth":true}_**
  // but it should be like this ( := means replace value, not add)
  //   **_{"type":"auth","action":"end","auth":true}_**

If it's the feature, not the bug, please explane, how i can parse 2 different json-messages.
The best, what I have found: 
  myJSONItem.Free; // to kill existing
  myJSONItem.Create; // to create new

Thanks,
DK.

**Comment by badunius** [comment]
Hi, this is definitely a bug. Assigning new code is supposed to overwrite the structure, not enrich it with the new values.
I fixed this (I believe) and pushed along with some new features and minor fixes.

**Comment by levran197** [comment]
It works. Thanks a lot.
