### ISSUE TITLE
Can't get arrays to work

### ISSUE THREAD

**Issue by stefan-karger** [badunius/myJSON#2]
Hi :)

This is what I do:

> carObj := myJSONItem.Create;
> carObj['vehicleType'].setStr('CAR');
> carObj['make'].setStr('BMW');
> 
> calcObj := myJSONItem.Create;
> calcObj['discount'].setNum(0);
> calcObj['effectiveInterest'].setNum(6.99);
> calcObj['term'].setInt(42);
> 
> reqObj := myJSONItem.Create;
> reqObj['vehicle'].setType(dtObject);
> reqObj['vehicle'].Code := carObj.Code;
> 
> reqObj['initialCalculationInput'].setType(dtArray);
> reqObj['initialCalculationInput'].Code := calcObj.Code;

This is what I get:

> {
>   "vehicle": {
>     "vehicletype": "CAR",
>     "make": "BMW"
>   },
>   "initialcalculationinput": {
>     "discount": 0,
>     "effectiveinterest": 6.99,
>     "term": 42
>   }
> }

But this is what I need:

> {
>   "vehicle": {
>     "vehicletype": "CAR",
>     "make": "BMW"
>   },
>   "initialcalculationinput": [
>     {
>       "discount": 0,
>       "effectiveinterest": 6.99,
>       "term": 42
>     }
>   ]
> }
> 

Would be awesome if you could help me with this cause I really love the simplicity of the Unit :)
And being stuck with Delphi7 at work it's kinda hard to get something that esy :D

**Comment by telmedola** [comment]
Hi.  I thought his library was very good and simple. So I decided to contribute to the code.
I already fixed this item and implemented a new method to add an array collection to the object. As soon as he releases the pullrequest, we can download it.

It will work like this:
  reqObj['initialCalculationInput'].setType(dtArray);
  reqObj['initialCalculationInput'].Code := carObj.Code;

Or, this:

  SetLength(aValues,0);
  for i := 0 to 10 do
  begin
    SetLength(aValues, Length(aValues)+1);
    aValues[Length(aValues)-1] := myJSONItem.Create;
    aValues[Length(aValues)-1]['discount'].setNum(i+1);
    aValues[Length(aValues)-1]['effectiveInterest'].setNum(6.99+i);
    aValues[Length(aValues)-1]['term'].setInt(43+i);
  end;

  reqObj['initialCalculationInput2'].setType(dtArray);
  reqObj['initialCalculationInput2'].setArray(aValues);

**Comment by otomazeli** [comment]
I was just trying to use this library and I notice that there is not method to set a normal array with primitive values like
Array of Int we could use the same setArray overloaded but not sure is the best
right now we can't create a {"MyArray": [1,4,5,6,6], "blabla":"blabla"} there is not method for that. Note that the array has not quotes

**Comment by badunius** [comment]
```pascal
reqObj['initialCalculationInput'].Code := calcObj.Code;
```
That where you overwrite an entire array under this key with an object
It may seem odd, but to access array items you should use the `value` accessor
```pascal
reqObj['initialCalculationInput'].Value[0].Code := calcObj.Code;
```
Or wrap the right hand side in square brackets 🤔
